### Send a new activity log to Kubernetes — LOGIN
POST http://34.67.185.46/api/logs
Content-Type: application/json

{
  "userId": "k8s_kubernetes_user",
  "action": "LOGIN",
  "metadata": {
    "browser": "Chrome",
    "cluster": "docker-desktop"
  }
}

###

### Send another log to Kubernetes — PAGE_VIEW
POST http://34.67.185.46/api/logs
Content-Type: application/json

{
  "userId": "k8s_user456",
  "action": "PAGE_VIEW",
  "metadata": {
    "page": "/k8s-dashboard"
  }
}

###

### Get all logs from Kubernetes (paginated)
GET http://34.67.185.46/api/logs

###

### Get logs filtered by userId from Kubernetes
GET http://34.67.185.46/api/logs?userId=k8s_kubernetes_user

###

### Kubernetes Health check
GET http://34.67.185.46/health
